export const PREMIUM_PLAN = {
  NONE: 'NONE',
  TRIAL: 'TRIAL',
  DAILY: 'DAILY',
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY',
  LIFETIME: 'LIFETIME'
} as const

export const PREMIUM_ERROR = {
  PREMIUM_REQUIRED: 'PREMIUM_REQUIRED'
} as const

export enum PREMIUM_PLAN_ENUM {
  DAILY = "DAILY",
  MONTHLY = "MONTHLY",
  YEARLY = "YEARLY",
  LIFETIME = "LIFETIME"
};
